### ISSUE TITLE
Blink Detection

### ISSUE THREAD

**Issue by sujan0991** [R4j4n/Eye-Gaze_and_Blink-detection-using-Neural-Network#3]
There are no script & dataset for blink detection model training. What kind of dataset(full face image or eye image) is used for blink detection model training.

**Comment by R4j4n** [comment]
Hello Sujan, 
If you need the dataset and training script I can provide you the files.

**Comment by baopmessi** [comment]
Hi @R4j4n . Can you share me the dataset and scripts of blinks detection. Thanks you
